// ui/components/buttons.slint

export component MenuItem {
    in property <string> text;
    in property <color> text-color: #cfcfcf;
    callback clicked;

    height: 24px;
    rect := Rectangle {
        background: transparent;
        border-radius: 3px;
        txt := Text {
            x: 8px;
            text: root.text;
            color: root.text-color;
            vertical-alignment: center;
            font-size: 12px;
        }
    }

    ta := TouchArea {
        clicked => { root.clicked(); }
    }

    states [
        hover when ta.has-hover: {
            rect.background: #3e6a90;
            txt.color: #ffffff;
        }
    ]
}

export component TabButton {
    in property <string> text;
    in property <bool> active;
    callback clicked;

    width: 100px;
    height: 26px;

    rect := Rectangle {
        background: active ? #3d3d3d : #1d1d1d;
        border-color: active ? #474747 : #353535;
        border-width: 1px;
        border-radius: 4px;

        animate background { duration: 100ms; }
        animate border-color { duration: 100ms; }

        txt := Text {
            text: root.text;
            color: active ? #ffffff : #808080;
            font-size: 13px;
            font-weight: active ? 600 : 400;
            horizontal-alignment: center;
            vertical-alignment: center;
            animate color { duration: 100ms; }
        }
    }

    ta := TouchArea {
        clicked => { root.clicked(); }
    }

    states [
        hover when ta.has-hover && !active: {
            rect.background: #2b2b2b;
            rect.border-color: #474747;
            txt.color: #cccccc;
        }
    ]
}

export component ChannelButton {
    in property <string> text;
    in property <color> active-color;
    in property <color> text-color: #ffffff;
    in property <bool> active;
    callback clicked;
    width: 26px;
    height: 26px;

    rect := Rectangle {
        background: active ? active-color : #1d1d1d;
        border-color: active ? #ffffff : #353535;
        border-width: active ? 1.5px : 1px;
        border-radius: 4px;

        txt := Text {
            text: root.text;
            color: active ? root.text-color : #cfcfcf;
            font-size: 12px;
            font-weight: 700;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }

    TouchArea {
        clicked => { clicked(); }
    }
}

export component CustomButton {
    in property <string> text;
    in property <bool> enabled: true;
    in property <color> primary-color: #3e6a90;
    in property <int> icon-type: 0; // 0: None, 1: Vector Image/Frame, 2: Vector List, 3: Vector Grid
    in property <bool> compact: false; // true
    callback clicked;

    height: 26px;
    min-width: (root.text == "" || compact) ? self.height : 90px;

    rect := Rectangle {
        background: !enabled ? #2d2d2d : primary-color;
        border-radius: 4px;
        border-width: 1px;
        border-color: !enabled ? #353535 : primary-color;
        opacity: !enabled ? 0.5 : 1.0;

        animate background { duration: 100ms; }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                alignment: center;
                spacing: root.text == "" ? 0px : 8px;
                padding-left: (root.text == "" || root.text == "..." || compact) ? 0px : 16px;
                padding-right: (root.text == "" || root.text == "..." || compact) ? 0px : 16px;

                if icon-type == 1: Rectangle {
                    width: 12px;
                    height: 12px;
                    border-color: !enabled ? #808080 : #ffffff;
                    border-width: 1px;
                    border-radius: 1px;
                    Path {
                        width: 100%;
                        height: 100%;
                        stroke: !enabled ? #808080 : #ffffff;
                        stroke-width: 1px;
                        commands: "M 1 9 L 3.5 5 L 5.5 7.5 L 7.5 3.5 L 11 10";
                    }
                }

                if icon-type == 2: Rectangle {
                    width: 12px;
                    height: 12px;
                    VerticalLayout {
                        spacing: 2px;
                        alignment: center;
                        Rectangle {
                            height: 1.5px;
                            background: !enabled ? #808080 : #ffffff;
                            border-radius: 0.5px;
                        }

                        Rectangle {
                            height: 1.5px;
                            background: !enabled ? #808080 : #ffffff;
                            border-radius: 0.5px;
                        }

                        Rectangle {
                            height: 1.5px;
                            background: !enabled ? #808080 : #ffffff;
                            border-radius: 0.5px;
                        }
                    }
                }

                if icon-type == 3: Rectangle {
                    width: 12px;
                    height: 12px;
                    GridLayout {
                        spacing: 1.5px;
                        Row {
                            Rectangle {
                                background: !enabled ? #808080 : #ffffff;
                                border-radius: 0.5px;
                            }

                            Rectangle {
                                background: !enabled ? #808080 : #ffffff;
                                border-radius: 0.5px;
                            }
                        }

                        Row {
                            Rectangle {
                                background: !enabled ? #808080 : #ffffff;
                                border-radius: 0.5px;
                            }

                            Rectangle {
                                background: !enabled ? #808080 : #ffffff;
                                border-radius: 0.5px;
                            }
                        }
                    }
                }

                if root.text != "": txt := Text {
                    text: root.text;
                    color: !enabled ? #808080 : #ffffff;
                    font-size: 11px;
                    font-weight: 600;
                    vertical-alignment: center;
                }
            }
        }
    }

    ta := TouchArea {
        enabled: root.enabled;
        clicked => { root.clicked(); }
    }

    states [
        hover when ta.has-hover && enabled: {
            rect.background: primary-color.brighter(12%);
        }
        active when ta.pressed && enabled: {
            rect.background: primary-color.darker(12%);
        }
    ]
}
