// ui/components/skipped_popup.slint

import { ListView } from "std-widgets.slint";
import { CustomButton } from "./buttons.slint";
import { Store } from "../store.slint";

export component SkippedFilesPopup inherits PopupWindow {
    width: 450px;
    height: 300px;
    close-policy: close-on-click;

    Rectangle {
        background: #2b2d31;
        border-color: #1f2023;
        border-width: 1.5px;
        border-radius: 4px;

        VerticalLayout {
            padding: 12px;
            spacing: 8px;

            Text {
                text: "Skipped / Corrupted Files List";
                font-weight: 700;
                color: #ffffff;
                font-size: 13px;
            }

            Rectangle {
                background: #111214;
                border-radius: 4px;
                vertical-stretch: 1;
                clip: true;

                ListView {
                    width: 100%;
                    height: 100%;

                    for file in Store.skipped_files_list: Rectangle {
                        height: 26px;
                        HorizontalLayout {
                            padding-left: 8px;
                            padding-right: 8px;

                            Text {
                                text: file;
                                color: #dcddde;
                                font-size: 11px;
                                vertical-alignment: center;
                                overflow: elide;
                            }
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: end;

                CustomButton {
                    text: "Dismiss";
                    clicked => { root.close(); }
                }
            }
        }
    }
}
